# Generated by Django 4.2.23 on 2025-06-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
