# Generated by Django 4.2.23 on 2025-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_booking_total_price_alter_guest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
